-- Enable UUID support in PostgreSQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- USER Table
CREATE TABLE Users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ROUTE Table
CREATE TABLE Routes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "from" VARCHAR(255) NOT NULL,
  "to" VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- STATION Table
CREATE TABLE Stations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  location VARCHAR(255) NOT NULL,
  routeId UUID NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (routeId) REFERENCES Routes(id) ON DELETE CASCADE
);

-- BUS Table
CREATE TABLE Buses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  departureTime TIME NOT NULL,
  arrivalTime TIME NOT NULL,
  seatAvailability INTEGER NOT NULL,
  routeId UUID NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (routeId) REFERENCES Routes(id) ON DELETE CASCADE
);

-- BOOKING Table
CREATE TABLE Bookings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bookingDate DATE NOT NULL,
  bookingTime TIME NOT NULL,
  busId UUID NOT NULL,
  userId UUID NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (busId) REFERENCES Buses(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
